#!/bin/bash
set -euo pipefail

GARAGE_HOST="${GARAGE_HOST:-127.0.0.1}"
GARAGE_CONFIG="/etc/garage.toml"
ENV_OUTPUT_DIR="/env"

echo "Waiting for Garage RPC at ${GARAGE_HOST}:3901..."
RPC_READY=0
STATUS_OUT=""
for i in $(seq 1 30); do
    STATUS_OUT=$(/usr/local/bin/garage -c "$GARAGE_CONFIG" status 2>&1) && {
        RPC_READY=1
        echo "$STATUS_OUT"
        break
    } || true
    echo "Attempt $i: $STATUS_OUT"
    sleep 1
done

if [ "$RPC_READY" -ne 1 ]; then
    echo "ERROR: Failed to connect to Garage RPC at ${GARAGE_HOST}:3901. Last output: $STATUS_OUT" >&2
    exit 1
fi

echo "Garage RPC connected. Retrieving node ID..."
NODE_ID=""
for i in $(seq 1 30); do
    RAW_NODE=$(/usr/local/bin/garage -c "$GARAGE_CONFIG" node id -q 2>/dev/null || true)
    if [ -n "$RAW_NODE" ]; then
        NODE_ID=$(echo "$RAW_NODE" | cut -d'@' -f1 | tr -d '[:space:]')
        if [ -n "$NODE_ID" ]; then
            break
        fi
    fi
    sleep 1
done

if [ -z "$NODE_ID" ]; then
    echo "ERROR: Failed to retrieve Garage node ID" >&2
    exit 1
fi
echo "Garage Node ID: $NODE_ID"

# 1. Assign and apply layout
echo "Configuring layout..."
CURRENT_LAYOUT=$(/usr/local/bin/garage -c "$GARAGE_CONFIG" layout show 2>/dev/null || true)
if echo "$CURRENT_LAYOUT" | grep -q "No layout role currently defined"; then
    /usr/local/bin/garage -c "$GARAGE_CONFIG" layout assign -z dc1 -c 10G "$NODE_ID"
    /usr/local/bin/garage -c "$GARAGE_CONFIG" layout apply --version 1
elif echo "$CURRENT_LAYOUT" | grep -q "No changes to apply"; then
    echo "Layout already applied."
else
    NEXT_VER=$(echo "$CURRENT_LAYOUT" | grep -o 'apply version: [0-9]*' | awk '{print $3}' || echo "1")
    /usr/local/bin/garage -c "$GARAGE_CONFIG" layout apply --version "$NEXT_VER" 2>/dev/null || true
fi

# 2. Create access key "winkey-dev"
echo "Setting up access key 'winkey-dev'..."
KEY_NAME="winkey-dev"
KEY_INFO=$(/usr/local/bin/garage -c "$GARAGE_CONFIG" key info "$KEY_NAME" 2>/dev/null || true)
if [ -z "$KEY_INFO" ]; then
    KEY_INFO=$(/usr/local/bin/garage -c "$GARAGE_CONFIG" key create "$KEY_NAME")
fi

ACCESS_KEY=$(echo "$KEY_INFO" | grep -i "Key ID:" | awk '{print $NF}' | tr -d '[:space:]')
SECRET_KEY=$(echo "$KEY_INFO" | grep -i "Secret key:" | awk '{print $NF}' | tr -d '[:space:]')

echo "Exporting credentials to ${ENV_OUTPUT_DIR}/.generated.env..."
cat <<EOF > "${ENV_OUTPUT_DIR}/.generated.env"
# Automatically generated by Garage bootstrap job — DO NOT COMMIT
AWS_ACCESS_KEY_ID=${ACCESS_KEY}
AWS_SECRET_ACCESS_KEY=${SECRET_KEY}
S3_ACCESS_KEY=${ACCESS_KEY}
S3_SECRET_KEY=${SECRET_KEY}
S3_REGION=garage
S3_ENDPOINT=http://${GARAGE_HOST}:3900
S3_PUBLIC_ENDPOINT=http://localhost:3900
EOF

# 3. Create buckets: winkey-raw, winkey-media, winkey-backups
for BUCKET in winkey-raw winkey-media winkey-backups; do
    echo "Ensuring bucket: $BUCKET..."
    /usr/local/bin/garage -c "$GARAGE_CONFIG" bucket info "$BUCKET" >/dev/null 2>&1 || \
        /usr/local/bin/garage -c "$GARAGE_CONFIG" bucket create "$BUCKET"
    /usr/local/bin/garage -c "$GARAGE_CONFIG" bucket allow --read --write --owner "$BUCKET" --key "$ACCESS_KEY"
done

# 4. Enable website hosting on winkey-media
echo "Enabling website hosting on winkey-media..."
/usr/local/bin/garage -c "$GARAGE_CONFIG" bucket website --allow winkey-media 2>/dev/null || \
/usr/local/bin/garage -c "$GARAGE_CONFIG" bucket website winkey-media --allow

# 5. Put CORS on winkey-raw: AllowedOrigins http://localhost:3000, AllowedMethods PUT/GET/HEAD, AllowedHeaders *, ExposeHeaders ETag, MaxAge 3600
echo "Configuring CORS on winkey-raw..."
cat <<EOF > /tmp/cors.json
{
  "CORSRules": [
    {
      "AllowedOrigins": ["http://localhost:3000"],
      "AllowedMethods": ["PUT", "GET", "HEAD"],
      "AllowedHeaders": ["*"],
      "ExposeHeaders": ["ETag"],
      "MaxAgeSeconds": 3600
    }
  ]
}
EOF

export AWS_ACCESS_KEY_ID="$ACCESS_KEY"
export AWS_SECRET_ACCESS_KEY="$SECRET_KEY"
export AWS_DEFAULT_REGION="garage"

for i in $(seq 1 30); do
    if aws --endpoint-url="http://${GARAGE_HOST}:3900" s3api put-bucket-cors --bucket winkey-raw --cors-configuration file:///tmp/cors.json 2>/dev/null; then
        echo "CORS applied to winkey-raw successfully."
        break
    fi
    sleep 1
done

echo "Garage bootstrap completed successfully."
