-- Task A2: RBAC administration and moderation.
--   auth   — suspension details on users + an append-only audit log of admin/moderator actions (auth-svc).
--   social — user reports on videos, comments and users; moderation state on the video projection (social-svc).
--   media  — moderator-hidden videos (video-svc).
-- IDs are UUIDv7 generated by the application (ADR-010). No cross-schema FKs (ADR-007).

-- auth -----------------------------------------------------------------------------------------------

-- status = 'SUSPENDED' already exists (000002). A suspension is either temporary (suspended_until set)
-- or indefinite (NULL); auth-svc treats a SUSPENDED user whose suspended_until has passed as ACTIVE and
-- flips the row back lazily on the next login/refresh. The API always stores a reason; the column stays
-- nullable for rows that were SUSPENDED before this migration.
ALTER TABLE auth.users
    ADD COLUMN suspended_until   timestamptz,
    ADD COLUMN suspension_reason text,
    ADD CONSTRAINT users_suspension_consistent CHECK (
        status = 'SUSPENDED' OR (suspended_until IS NULL AND suspension_reason IS NULL)),
    ADD CONSTRAINT users_suspension_reason_len CHECK (
        suspension_reason IS NULL OR char_length(suspension_reason) BETWEEN 1 AND 500);

CREATE TYPE auth.audit_action AS ENUM (
    'USER_ROLES_CHANGED',
    'USER_SUSPENDED',
    'USER_UNSUSPENDED'
);

-- Written in the same transaction as the change it records. Never updated or deleted by the service.
CREATE TABLE auth.audit_log (
    id             uuid PRIMARY KEY,
    actor_id       uuid NOT NULL,             -- auth.users.id of the admin/moderator
    action         auth.audit_action NOT NULL,
    target_user_id uuid NOT NULL,
    details        jsonb NOT NULL DEFAULT '{}'::jsonb,  -- e.g. {"from":["viewer"],"to":["viewer","moderator"]}
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_log_created ON auth.audit_log (created_at DESC, id DESC);
CREATE INDEX audit_log_target ON auth.audit_log (target_user_id, created_at DESC, id DESC);

-- Admin user search by email/handle prefix and display name (GET /v1/admin/users?q=).
CREATE INDEX users_display_name_trgm ON auth.users USING gin (display_name gin_trgm_ops);
CREATE INDEX users_created ON auth.users (created_at DESC, id DESC);

-- social ---------------------------------------------------------------------------------------------

CREATE TYPE social.report_target AS ENUM ('VIDEO', 'COMMENT', 'USER');
CREATE TYPE social.report_reason AS ENUM (
    'SPAM', 'HARASSMENT', 'HATE', 'SEXUAL', 'VIOLENCE', 'COPYRIGHT', 'MISINFORMATION', 'OTHER'
);
CREATE TYPE social.report_status AS ENUM ('OPEN', 'ACTIONED', 'DISMISSED');

CREATE TABLE social.reports (
    id              uuid PRIMARY KEY,
    reporter_id     uuid NOT NULL,
    target_type     social.report_target NOT NULL,
    target_id       uuid NOT NULL,             -- media.videos.id, social.comments.id or auth.users.id
    reason          social.report_reason NOT NULL,
    note            text NOT NULL DEFAULT '',
    status          social.report_status NOT NULL DEFAULT 'OPEN',
    resolved_by     uuid,
    resolution_note text,
    resolved_at     timestamptz,
    created_at      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT reports_note_len CHECK (char_length(note) <= 500),
    CONSTRAINT reports_resolution_len CHECK (resolution_note IS NULL OR char_length(resolution_note) <= 500),
    CONSTRAINT reports_resolved_consistent CHECK (
        (status = 'OPEN' AND resolved_by IS NULL AND resolved_at IS NULL)
        OR (status <> 'OPEN' AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL))
);
-- One open report per reporter and target: a repeat report returns the existing one.
CREATE UNIQUE INDEX reports_one_open_per_reporter
    ON social.reports (reporter_id, target_type, target_id) WHERE status = 'OPEN';
-- Moderation queue: open reports grouped by target, oldest first.
CREATE INDEX reports_queue ON social.reports (status, target_type, target_id, created_at);
CREATE INDEX reports_created ON social.reports (status, created_at, id);

-- Projection of video.moderated: a hidden video accepts no new comments or likes.
ALTER TABLE social.videos
    ADD COLUMN hidden boolean NOT NULL DEFAULT false;

-- media ----------------------------------------------------------------------------------------------

CREATE TYPE media.moderation_state AS ENUM ('VISIBLE', 'HIDDEN');

ALTER TABLE media.videos
    ADD COLUMN moderation_state  media.moderation_state NOT NULL DEFAULT 'VISIBLE',
    ADD COLUMN moderation_reason text,
    ADD COLUMN moderated_by      uuid,
    ADD COLUMN moderated_at      timestamptz,
    ADD CONSTRAINT videos_moderation_consistent CHECK (
        (moderation_state = 'VISIBLE' AND moderation_reason IS NULL)
        OR (moderation_state = 'HIDDEN' AND moderation_reason IS NOT NULL
            AND moderated_by IS NOT NULL AND moderated_at IS NOT NULL)),
    ADD CONSTRAINT videos_moderation_reason_len CHECK (
        moderation_reason IS NULL OR char_length(moderation_reason) BETWEEN 1 AND 500);
