-- social schema — owned by social-svc (task C1): comments (2 levels), video likes, channel subscriptions.
-- IDs are UUIDv7 generated by the application (ADR-010). No cross-schema FKs (ADR-007): video and user
-- ids are plain uuids; videos are known through the social.videos projection fed by video.ready /
-- video.deleted, users through the auth.public_profiles view.

CREATE SCHEMA IF NOT EXISTS social;

CREATE TYPE social.comment_status AS ENUM ('VISIBLE', 'DELETED', 'HIDDEN');

-- Projection of videos that can receive comments and likes. Inserted on video.ready (upsert, a re-encode
-- sends it again) and deleted on video.deleted, which cascades to comments and likes.
CREATE TABLE social.videos (
    id            uuid PRIMARY KEY,           -- media.videos.id
    owner_id      uuid NOT NULL,              -- channel that may moderate comments on this video
    like_count    bigint NOT NULL DEFAULT 0,  -- maintained by trigger
    comment_count bigint NOT NULL DEFAULT 0,  -- VISIBLE comments incl. replies; maintained by trigger
    created_at    timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT social_videos_counts CHECK (like_count >= 0 AND comment_count >= 0)
);

CREATE TABLE social.comments (
    id          uuid PRIMARY KEY,
    video_id    uuid NOT NULL REFERENCES social.videos (id) ON DELETE CASCADE,
    author_id   uuid NOT NULL,
    parent_id   uuid REFERENCES social.comments (id) ON DELETE CASCADE,  -- NULL = top level
    body        text NOT NULL,
    status      social.comment_status NOT NULL DEFAULT 'VISIBLE',
    reply_count integer NOT NULL DEFAULT 0,   -- VISIBLE replies; maintained by trigger
    edited_at   timestamptz,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    -- HIDDEN keeps the body so a moderator can restore it; DELETED (by author/owner) wipes it.
    CONSTRAINT comments_body_len CHECK (status = 'DELETED' OR char_length(body) BETWEEN 1 AND 2000),
    CONSTRAINT comments_deleted_empty CHECK (status <> 'DELETED' OR body = ''),
    CONSTRAINT comments_not_own_parent CHECK (parent_id IS NULL OR parent_id <> id),
    CONSTRAINT comments_reply_count CHECK (reply_count >= 0)
);
CREATE INDEX comments_top_level ON social.comments (video_id, created_at DESC, id DESC) WHERE parent_id IS NULL;
CREATE INDEX comments_replies ON social.comments (parent_id, created_at, id) WHERE parent_id IS NOT NULL;
CREATE INDEX comments_author ON social.comments (author_id, created_at DESC);

-- Only body/status edits bump updated_at, so counter updates on a parent do not.
CREATE TRIGGER comments_set_updated_at
    BEFORE UPDATE OF body, status ON social.comments
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Exactly two levels: a reply's parent must be a top-level comment on the same video.
CREATE FUNCTION social.guard_comment_parent() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    p_video  uuid;
    p_parent uuid;
BEGIN
    IF NEW.parent_id IS NULL THEN
        RETURN NEW;
    END IF;
    SELECT video_id, parent_id INTO p_video, p_parent FROM social.comments WHERE id = NEW.parent_id;
    IF NOT FOUND THEN
        RETURN NEW;  -- the foreign key reports it
    END IF;
    IF p_parent IS NOT NULL THEN
        RAISE EXCEPTION 'comment % replies to a reply (only two levels allowed)', NEW.id
            USING ERRCODE = 'check_violation';
    END IF;
    IF p_video <> NEW.video_id THEN
        RAISE EXCEPTION 'comment % replies to a comment on another video', NEW.id
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER comments_guard_parent
    BEFORE INSERT OR UPDATE OF parent_id, video_id ON social.comments
    FOR EACH ROW EXECUTE FUNCTION social.guard_comment_parent();

-- comment_count / reply_count follow VISIBLE transitions (insert, hide, delete, restore).
CREATE FUNCTION social.comment_counts() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    d integer := 0;
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status = 'VISIBLE' THEN d := 1; END IF;
    ELSIF OLD.status = 'VISIBLE' AND NEW.status <> 'VISIBLE' THEN
        d := -1;
    ELSIF OLD.status <> 'VISIBLE' AND NEW.status = 'VISIBLE' THEN
        d := 1;
    END IF;
    IF d = 0 THEN
        RETURN NULL;
    END IF;
    UPDATE social.videos SET comment_count = comment_count + d WHERE id = NEW.video_id;
    IF NEW.parent_id IS NOT NULL THEN
        UPDATE social.comments SET reply_count = reply_count + d WHERE id = NEW.parent_id;
    END IF;
    RETURN NULL;
END
$$;

CREATE TRIGGER comments_counts
    AFTER INSERT OR UPDATE OF status ON social.comments
    FOR EACH ROW EXECUTE FUNCTION social.comment_counts();

CREATE TABLE social.video_likes (
    video_id   uuid NOT NULL REFERENCES social.videos (id) ON DELETE CASCADE,
    user_id    uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (video_id, user_id)
);
CREATE INDEX video_likes_user ON social.video_likes (user_id, created_at DESC);

CREATE FUNCTION social.like_counts() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE social.videos SET like_count = like_count + 1 WHERE id = NEW.video_id;
    ELSE
        UPDATE social.videos SET like_count = like_count - 1 WHERE id = OLD.video_id;
    END IF;
    RETURN NULL;
END
$$;

CREATE TRIGGER video_likes_counts
    AFTER INSERT OR DELETE ON social.video_likes
    FOR EACH ROW EXECUTE FUNCTION social.like_counts();

-- Channel = user id of the creator. Rows appear on the first subscription.
CREATE TABLE social.channels (
    id               uuid PRIMARY KEY,
    subscriber_count bigint NOT NULL DEFAULT 0 CHECK (subscriber_count >= 0)
);

CREATE TABLE social.subscriptions (
    subscriber_id uuid NOT NULL,
    channel_id    uuid NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (subscriber_id, channel_id),
    CONSTRAINT subscriptions_not_self CHECK (subscriber_id <> channel_id)
);
CREATE INDEX subscriptions_channel ON social.subscriptions (channel_id, created_at DESC);
CREATE INDEX subscriptions_subscriber_recent ON social.subscriptions (subscriber_id, created_at DESC);

CREATE FUNCTION social.subscriber_counts() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO social.channels AS c (id, subscriber_count) VALUES (NEW.channel_id, 1)
        ON CONFLICT (id) DO UPDATE SET subscriber_count = c.subscriber_count + 1;
    ELSE
        UPDATE social.channels SET subscriber_count = subscriber_count - 1 WHERE id = OLD.channel_id;
    END IF;
    RETURN NULL;
END
$$;

CREATE TRIGGER subscriptions_counts
    AFTER INSERT OR DELETE ON social.subscriptions
    FOR EACH ROW EXECUTE FUNCTION social.subscriber_counts();

CREATE TABLE social.outbox (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id     uuid NOT NULL UNIQUE,
    subject      text NOT NULL,
    payload      jsonb NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz
);
CREATE INDEX social_outbox_pending ON social.outbox (id) WHERE published_at IS NULL;
