version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'
    groups:
      github-actions:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain root & workspace Node dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps'
    groups:
      npm:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain Go dependencies in libs/go
  - package-ecosystem: 'gomod'
    directory: '/libs/go'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps(libs/go)'
    groups:
      gomod:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain Go dependencies in services/upload
  - package-ecosystem: 'gomod'
    directory: '/services/upload'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps(upload)'
    groups:
      gomod:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain Go dependencies in services/transcoder
  - package-ecosystem: 'gomod'
    directory: '/services/transcoder'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps(transcoder)'
    groups:
      gomod:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain Go dependencies in services/video
  - package-ecosystem: 'gomod'
    directory: '/services/video'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps(video)'
    groups:
      gomod:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain Go dependencies in services/analytics
  - package-ecosystem: 'gomod'
    directory: '/services/analytics'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps(analytics)'
    groups:
      gomod:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']

  # Maintain Docker dependencies in deploy/compose
  - package-ecosystem: 'docker'
    directory: '/deploy/compose'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deploy'
    groups:
      docker:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
