version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'ci'

  # Maintain root & workspace Node dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps'

  # Maintain Go dependencies in libs/go
  - package-ecosystem: 'gomod'
    directory: '/libs/go'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps(libs/go)'

  # Maintain Go dependencies in services/upload
  - package-ecosystem: 'gomod'
    directory: '/services/upload'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps(upload)'

  # Maintain Go dependencies in services/transcoder
  - package-ecosystem: 'gomod'
    directory: '/services/transcoder'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deps(transcoder)'

  # Maintain Docker dependencies in deploy/compose
  - package-ecosystem: 'docker'
    directory: '/deploy/compose'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'deploy'
