apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-web
    digest: sha256:0f2545bf5118c641f063d04bc8bfe136693667427207275d9d9151ac058efb9c
