apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-web
    digest: sha256:7aa7346c6a937d6031e757b50f4ad31a68a27a297386cbbf451c04153693e8b6
