apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-web
    digest: sha256:f70ce43b3b8fdf75dccd9a49586d53515b66d5a175585904ca4cc47c7ab8478d
