apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-video
    digest: sha256:aa846ad01a3250f8aaf3aa43970bb4ef9ac26161184f0d1c4fb2fb3fa6259eda
