apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-video
    digest: sha256:e3f226ff3f9e79224f1fef9139c4f448e647bb4698ce6db0b43db962932dba13
