apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-video
    digest: sha256:61f51983855b69244b85661e8a049977f1453a92a06c598a919324831a4702c5
