apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://127.0.0.1:8428
    isDefault: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.50.0
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://127.0.0.1:3100
    isDefault: false
    jsonData:
      maxLines: 1000
    editable: false

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: 127.0.0.1
      port: 8123
      protocol: http
      username: grafana_ro
      defaultDatabase: winkey
    secureJsonData:
      password: $CLICKHOUSE_GRAFANA_RO_PASSWORD
    editable: false
