-- auth schema — owned by auth-svc (tasks A1, A2).
-- IDs are UUIDv7 generated by the application (ADR-010), so there are no column defaults for them.

CREATE TYPE auth.role AS ENUM ('viewer', 'creator', 'moderator', 'admin');
CREATE TYPE auth.user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'DELETED');

CREATE TABLE auth.users (
    id                uuid PRIMARY KEY,
    email             citext NOT NULL UNIQUE,
    email_verified_at timestamptz,
    password_hash     text,                 -- argon2id PHC string; NULL for OAuth-only accounts
    handle            citext NOT NULL UNIQUE,
    display_name      text NOT NULL,
    avatar_key        text,                 -- object key in the media bucket
    roles             auth.role[] NOT NULL DEFAULT '{viewer,creator}',
    status            auth.user_status NOT NULL DEFAULT 'ACTIVE',
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_handle_format CHECK (handle::text ~ '^[A-Za-z0-9_.]{3,30}$'),
    CONSTRAINT users_display_name_len CHECK (char_length(display_name) BETWEEN 1 AND 50),
    CONSTRAINT users_roles_not_empty CHECK (cardinality(roles) > 0)
);

CREATE TRIGGER users_set_updated_at
    BEFORE UPDATE ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE auth.oauth_identities (
    provider   text NOT NULL,               -- 'google'
    subject    text NOT NULL,               -- provider's stable user id ("sub")
    user_id    uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    email      citext,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (provider, subject)
);
CREATE INDEX oauth_identities_user_id ON auth.oauth_identities (user_id);

-- Refresh tokens rotate on every use. All tokens of one sign-in share a family_id;
-- presenting a token that was already rotated revokes the whole family (reuse detection).
CREATE TABLE auth.refresh_tokens (
    id          uuid PRIMARY KEY,
    user_id     uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    family_id   uuid NOT NULL,
    token_hash  bytea NOT NULL UNIQUE,      -- SHA-256 of the opaque token; the token itself is never stored
    parent_id   uuid REFERENCES auth.refresh_tokens (id) ON DELETE SET NULL,
    issued_at   timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz NOT NULL,
    rotated_at  timestamptz,
    revoked_at  timestamptz,
    user_agent  text,
    ip          inet,
    CONSTRAINT refresh_tokens_hash_len CHECK (octet_length(token_hash) = 32),
    CONSTRAINT refresh_tokens_expiry CHECK (expires_at > issued_at)
);
CREATE INDEX refresh_tokens_family ON auth.refresh_tokens (family_id);
CREATE INDEX refresh_tokens_user_active ON auth.refresh_tokens (user_id) WHERE revoked_at IS NULL;
CREATE INDEX refresh_tokens_expires ON auth.refresh_tokens (expires_at);

CREATE TABLE auth.outbox (
    id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id     uuid NOT NULL UNIQUE,
    subject      text NOT NULL,
    payload      jsonb NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    published_at timestamptz
);
CREATE INDEX auth_outbox_pending ON auth.outbox (id) WHERE published_at IS NULL;

-- The only auth data other services may read (ADR-007). Grant SELECT on this view, not on auth.users.
CREATE VIEW auth.public_profiles AS
SELECT id, handle::text AS handle, display_name, avatar_key
FROM auth.users
WHERE status = 'ACTIVE';
