apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-upload
    digest: sha256:c05f76af2dc510f7000fdb5c1146d0899fcbf38a520c5d963a7e63e28f81ac03
