apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-upload
    digest: sha256:590c66600ee6f52b4881c086f79ff5e54132d32c317799059bf812d475bd64ad
