apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-upload
    digest: sha256:196bf32208c94de43c272317a59c89efd40f6ba5e45e828dcb31665bd2d42318
