apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vmagent-data
  namespace: observability
  labels:
    app.kubernetes.io/name: vmagent
    app.kubernetes.io/part-of: winkey
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
