entryPoints:
  web:
    address: ':8080'
  traefik:
    address: ':8082'

providers:
  file:
    filename: '/etc/traefik/dynamic.yml'
    watch: true

api:
  dashboard: true
  insecure: true

ping:
  entryPoint: 'web'

log:
  level: INFO
  format: json

accessLog:
  format: json
