apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-auth
    digest: sha256:941a9eb419bc6141910a79199f631b89554e39f509a49d0a0493a8a785ba7b72
