apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-auth
    digest: sha256:6c71853d88acc0579f0c5a63e3f11b901fe3c57e4d7e9d72c7dcc25d974f0f39
