apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-auth
    digest: sha256:92f8e68d9ff7ac949ab520486ec074aa2e0a0d839864d72533ff5f22af579add
