apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: default
  labels:
    app.kubernetes.io/name: auth-svc
    app.kubernetes.io/part-of: winkey
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app.kubernetes.io/name: auth-svc
