apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-realtime
    digest: sha256:60ba3e6deddf1196c0ff7d1b96d558f83c6a320f56d62f6278536d2e9230adad
