apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-realtime
    digest: sha256:a084b20df44ad67ddeb3b569696b7a6c4466f0b92e03579ad3d7870cf0817b92
