apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-realtime
    digest: sha256:f1a1e55c590fbc69efab5354d02cfa232ccf062ebe5f339280c96506998670bb
