apiVersion: v1
kind: Service
metadata:
  name: realtime-svc
  namespace: default
  labels:
    app.kubernetes.io/name: realtime-svc
    app.kubernetes.io/part-of: winkey
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3005
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: realtime-svc
