apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-social
    digest: sha256:0ba727c923ea0566fa09e26e6f2fbf7571a0b318bc7d176e4d826dbae50ae21f
