apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-social
    digest: sha256:c3a72439cab7df18c58235828a0facbf3083dd0f9381406c72309fa2537705e0
