apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/luantpbk/winkey-social
    digest: sha256:dc961b73a8c8d8db7d7f5e292abe10705dd4a83ab64dddd963638a5a938693ea
